### ISSUE TITLE
Cleanup suggestion

### ISSUE THREAD

**Issue by iantrich** [ljmerza/fitbit-card#1]
I don't think you need the "Minutes" or "Resting" under the gauges. A single line for each would look a lot cleaner IMO. Good stuff, wish I still had my fitbit now :)

**Comment by ljmerza** [comment]
Those units of measurements come directly from the `unit_of_measurment` on each entity. I agree they can be too long which is why I added the ability to hide units. There is also a heart rate sensor you can use instead of the resting heart rate sensor. Maybe should have used that one for the example

**Comment by iantrich** [comment]
PR to backend worth it? Probably not. People can give a friendly name if they want.

**Comment by ljmerza** [comment]
yeah i can add being able to customize the units.

**Comment by ljmerza** [comment]
ha funny enough I did add that feature but forgot to include it on the readme. it was `text` though so changed it to `units` and pushed a new version. Thanks!

**Comment by iantrich** [comment]
😂
